version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db
    container_name: bl-mongo-dev

  server:
    image: bl-backend-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    ports:
      - 3003:3003
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - SECRET=usemetohash911
      - PORT=3003
    container_name: bl-backend-dev1
    depends_on:
      - mongo

  app:
    image: bl-frontend-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: bl-frontend-dev1

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bl-revproxy-dev
    depends_on:
      - app
      - server
